spring:
  application:
    name: video-service

  data:
    mongodb:
      uri: ${MONGO_URI}

  output:
    ansi:
      enabled: ALWAYS

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://seu-auth.com/

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

aws:
  region: us-east-1
  s3:
    bucket: video-storage-bucket-ter1

sqs:
  queue:
    url: ${SQS_QUEUE_URL}

security:
  jwt:
    enabled: false

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        security: INFO
        security.oauth2: INFO
        boot:
          actuate:
            health: INFO

management:
  health:
    mongo:
      enabled: false
