
spring:
  application:
    name: video-service

  output:
    ansi:
      enabled: ALWAYS

  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@video-db.yjexuqs.mongodb.net/video-db?retryWrites=true&w=majority&appName=video-db

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://seu-auth.com/

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}


aws:
  region: us-east-1
  s3:
    bucket: video-storage-bucket-ter1

sqs:
  queue:
    url: ${SQS_QUEUE_URL}

security:
  jwt:
    enabled: false

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        security.oauth2: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: loggers
