name: Build and Deploy to AWS Fargate
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SQS_QUEUE_URL: ${{ secrets.SQS_QUEUE_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Permissão no Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build com Maven
        run: ./mvnw clean package -DskipTests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login no ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin 409139324592.dkr.ecr.us-east-1.amazonaws.com

      - name: Build da imagem Docker
        run: |
          docker build -t video-service-1 .
          docker tag video-service-1:latest 409139324592.dkr.ecr.us-east-1.amazonaws.com/video-service-1:latest

      - name: Push para o ECR
        run: |
          docker push 409139324592.dkr.ecr.us-east-1.amazonaws.com/video-service-1:latest

